
name: PR Checker

on:
  - pull_request

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Doc version checker
    runs-on: ubuntu-20.04
    steps:
      - name: Config action
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.4'
      - name: Check version docs
        run: |
          npm i node-os-utils
          cd "${GITHUB_WORKSPACE}/"
          node .github/scripts/checker.version.js
          status=$?
          [ $status -eq 0 ] && echo "Version checker passed" || exit 1
          exit 0
